name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building the application..."
        
      - name: Install dependencies
        run: npm install
         
      - name: Build application
        run: npm run build

      - name: Build Done message
        run: echo "Build created and stored sucessfully"
